# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HledgerPriceTracker < Formula
  desc "CLI tool to get market prices for commodities"
  homepage "https://github.com/lentidas/hledger-price-tracker"
  version "0.1.4"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lentidas/hledger-price-tracker/releases/download/v0.1.4/hledger-price-tracker_Darwin_x86_64.tar.gz"
      sha256 "36cf4fb335c52baef48b2a010422b3de23323f05f2855ea459673fe86cac7817"

      def install
        bin.install "hledger-price-tracker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lentidas/hledger-price-tracker/releases/download/v0.1.4/hledger-price-tracker_Darwin_arm64.tar.gz"
      sha256 "a151d664ea1c871c1028e537556f60624594e1a028eb391370fa4336a6a9f0e0"

      def install
        bin.install "hledger-price-tracker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lentidas/hledger-price-tracker/releases/download/v0.1.4/hledger-price-tracker_Linux_x86_64.tar.gz"
        sha256 "0a4d13b60220cb40cfadf0ac1cbb89285b88df0e6a8d846fa10685f1850a463d"

        def install
          bin.install "hledger-price-tracker"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lentidas/hledger-price-tracker/releases/download/v0.1.4/hledger-price-tracker_Linux_arm64.tar.gz"
        sha256 "0e7569625aa8e82809029665641f4035394ca538d1ba92c90d7c97285b2c3740"

        def install
          bin.install "hledger-price-tracker"
        end
      end
    end
  end
end
