# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HledgerPriceTracker < Formula
  desc "CLI tool to get market prices for commodities"
  homepage "https://github.com/lentidas/hledger-price-tracker"
  version "0.1.3"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lentidas/hledger-price-tracker/releases/download/v0.1.3/hledger-price-tracker_Darwin_x86_64.tar.gz"
      sha256 "9474f5c0ec3354e34d59621f73c561a6eed16fc595ad498ab74a7219ab93b0da"

      def install
        bin.install "hledger-price-tracker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lentidas/hledger-price-tracker/releases/download/v0.1.3/hledger-price-tracker_Darwin_arm64.tar.gz"
      sha256 "65a2306b6723b5c7c6938363fd3c0e1b4bb953ed511153087e7e99bb71364899"

      def install
        bin.install "hledger-price-tracker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lentidas/hledger-price-tracker/releases/download/v0.1.3/hledger-price-tracker_Linux_x86_64.tar.gz"
        sha256 "450c4cb444054e0797845fcde2349a514ee91c7ab4563d15939c3107f45a8e30"

        def install
          bin.install "hledger-price-tracker"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lentidas/hledger-price-tracker/releases/download/v0.1.3/hledger-price-tracker_Linux_arm64.tar.gz"
        sha256 "02a251e6eebcf88519ce6ca7d34b9baa39d885ffa7c5a72f5d688fc4086ac061"

        def install
          bin.install "hledger-price-tracker"
        end
      end
    end
  end
end
